#POTABILITY OF WATER


#Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Reading the dataset

In [ ]:
data = pd.read_csv("/content/water_potability.csv")
data.head()

ph    Hardness       Solids  ...  Organic_carbon  Turbidity  Potability
0       NaN  204.890456  20791.31898  ...       10.379783   2.963135           0
1  3.716080  129.422921  18630.05786  ...       15.180013   4.500656           0
2  8.099124  224.236259  19909.54173  ...       16.868637   3.055934           0
3  8.316766  214.373394  22018.41744  ...       18.436525   4.628771           0
4  9.092223  181.101509  17978.98634  ...       11.558279   4.075075           0

[5 rows x 8 columns]

In [ ]:
data.describe()

ph     Hardness  ...    Turbidity   Potability
count  2785.000000  3276.000000  ...  3276.000000  3276.000000
mean      7.080795   196.369496  ...     3.966786     0.390110
std       1.594320    32.879761  ...     0.780382     0.487849
min       0.000000    47.432000  ...     1.450000     0.000000
25%       6.093092   176.850538  ...     3.439711     0.000000
50%       7.036752   196.967627  ...     3.955028     0.000000
75%       8.062066   216.667456  ...     4.500320     1.000000
max      14.000000   323.124000  ...     6.739000     1.000000

[8 rows x 8 columns]

#Identifying missing values

In [ ]:
data.isnull().sum()

ph                491
Hardness            0
Solids              0
Chloramines         0
Conductivity        0
Organic_carbon      0
Turbidity           0
Potability          0
dtype: int64


#Filling all missing values using Mean, median or Mode

In [ ]:
x = data['ph'].mean()
data['ph'].fillna(x, inplace = True)

In [ ]:
data.isnull().sum()

ph                0
Hardness          0
Solids            0
Chloramines       0
Conductivity      0
Organic_carbon    0
Turbidity         0
Potability        0
dtype: int64

#Initiating the variables

In [ ]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

#Splitting dataset into training and testing dataset

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[-0.31737702,  0.20204646, -0.55463361, ..., -0.19929648,
         0.50622105, -1.3411035 ],
       [-0.27560552, -0.08006604,  1.36873646, ...,  0.88258563,
        -1.65420736,  0.09082874],
       [-0.17210349,  0.28302116, -0.42399002, ...,  0.83848598,
        -0.13486017,  1.27418303],
       ...,
       [-0.31276111, -0.29742012,  1.00441877, ..., -1.17703712,
        -0.13277954, -0.60244883],
       [ 1.15935349,  0.66263542, -0.66599679, ..., -0.46073018,
         0.6401932 ,  0.40337428],
       [-0.26640542,  0.05640763,  1.42745437, ...,  0.05560965,
        -0.63182689, -0.25894741]])

#Training the model using KNN Algorithm

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion= 'gini')
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

#testing

In [ ]:

y_pred = classifier.predict(X_test)


#Checking the performance

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[258 154]
 [133 111]]


0.5625

#Prediction for the new value

In [ ]:
output= classifier.predict(sc.transform([[3.17608,129.42,18630.06,6.63,592.8,15.18,4.5]]))
output

array([1])

In [ ]:
output= classifier.predict([[3.17608,129.42,18630.06,6.63,592.8,15.18,4.5]])
output

array([1])

In [ ]:
output = classifier.predict(sc.transform([[10.04,113.83,16266.43,7.93,557.4861,13.19,3.80]]))
output

array([0])